version: "3.9"

services:
  db:
    image: postgres:15
    container_name: reuse_db
    restart: always
    environment:
      POSTGRES_DB: reuse_db
      POSTGRES_USER: reuse_user
      POSTGRES_PASSWORD: reuse_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   container_name: reuse_app
  #   restart: always
  #   env_file:
  #     - .env.docker
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app
  #   command: npm run dev

volumes:
  postgres-data:
