services:
  db:
    build:
      context: ./postgresdb
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: application
    ports:
      - "5432:5432"

volumes:
  postgres-data:
