export enum CategoryCode {
  CLOTHING = "ROUPAS",
  HOUSE = "CASA",
  FOOTWEAR = "CALÇADOS",
  ACCESSORIES = "ACESSÓRIOS",
  COSMETICS = "COSMÉTICOS",
  OTHERS = "OUTROS",
}

export enum CategoryDescription {
  CLOTHING = "ROUPAS",
  HOUSE = "CASA",
  FOOTWEAR = "CALÇADOS",
  ACCESSORIES = "ACESSÓRIOS",
  COSMETICS = "COSMÉTICOS",
  OTHERS = "OUTROS",
}
